### PR TITLE
implemented flattern for stack:tree and support for {Fn::GetAtt:[resource,attribute]}

### PR DESCRIPTION
**Pull request by dng-dev**
Hey @fbrnc  i added the flattern of the tree and also the possibility for inline {Fn::GetAtt:[resource,attribute]} which is an feature request by you #31 
bildschirmfoto 2016-08-27 um 21 58 09

### CODE REVIEW

**Comment by dng-dev** [comment]
Hey @fbrnc if you merge it, can we make a version bump?
output of the tree command

**Comment by fbrnc** [comment]
You're awesome! Thanks for picking this up and implementing this so quickly. I'll test the tree later today, but here's already one thing I noticed about the Fn:GetAtt feature:

The regex you're using does not allow adding whitespace everywhere. E.g. `EIP="{Fn::GetAtt:[NatIp,AllocationId] }"` (notice the extra space before the last `}`) would not be a match. 

While of course it's easy to fix that I'd like to suggest a simpler snytax that also matches the scheme of other inline functions and value lookups:

`{Attribute:<resource>:<attribure>}`
(your example then would be `{Attribute:NatIp:AllocationId}`

What do you think?

**Comment by dng-dev** [comment]
Hey @fbrnc i will fix the regex you are right. I don't think its an good idea to introduce a new syntax for the Fn::GetAtt part. I think it can produce more confusion. But the final decision is up to you.

**Comment by dng-dev** [comment]
Hey @fbrnc i updated the regex in the simulator. When you have time play around. If you don't see problems, i will update the regexp.

[https://regex101.com/r/vN8qT9/2](https://regex101.com/r/vN8qT9/2)

**Comment by dng-dev** [comment]
Hey @fbrnc i updated the regexp

**Pull request merged**
