### PR TITLE
stack:tree command

### PR DESCRIPTION
**Pull request by dng-dev**
its might be useful to view the stacks as tree.
bildschirmfoto 2016-08-24 um 00 52 20

### CODE REVIEW

**Comment by fbrnc** [comment]
Wow, thanks a lot @dng-dev! Please add yourself as contributor to the README.md and composer.json file. That's great stuff!

**Comment by fbrnc** [comment]
I just tested it and it looks great!
However it would be nice if the tree would be flattened if there is only one child node (this way it's a lot shorter and better to read)

Example:

```
.
├── app
│   ├── dpl
│   │   └── base-vpc-deploy
```

**Comment by fbrnc** [comment]
We'll probably have to post-process the `$dataTree`returned from `prepareTree()` and go back and recursively merge parent key and child key if the child array has only a single element. 
Doesn't sound trivial, but would probably have a nice effect.

This should not only apply to leave nodes, but could also apply to nodes in between:
If there's a-b-c and a-b-d, then 'a-b' should not be split into two hierarchies.

We should probably add this as a separate issue and maybe one day we'll get to this :)

**Comment by dng-dev** [comment]
Currently preparing another pull request for the lazy developers. When i
find time today i will implement it. But will bring more complex logic to
the code.

2016-08-24 11:05 GMT+02:00 Fabrizio Branca notifications@github.com:

**Pull request merged**
